version: "3.4"

services:
  identifier:
    ports:
      - "80:80"

  triplestore:
    ports:
      - "8890:8890"

  poc-hackathon:
    ports:
      - "2000:80"

  resource:
    ports:
      - "3000:80"